import type { Metadata } from "next"
import "./globals.css"
import Navbar from "@/components/navbar/navbar"
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "next-themes"
import Header from "@/components/header/header"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <Header />

            {children}
          
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
